---
  - name: Obtener lista de contenedores
    containers.podman.podman_container_info:
      executable: podman
      containers: all
    register: podman_containers

  - name: Recoger información de contenedores
    command: podman ps --format "{{ json . }}"
    register: result

  - name: Procesar información para extraer datos relevantes
    set_fact:
      containers: "{{ result.stdout_lines | map('from_json') }}"
      
  - name: Mostrar nombre y estado de los contenedores
    debug:
      msg:
        Nombre: "{{ item.Names }}"
        Estado: "{{ item.State }}"
    loop: "{{ containers }}"

  - name: Reiniciar contenedores que no estén en estado running
    containers.podman.podman_container:
      name: "{{ item.Name }}"
      state: started
    with_items: "{{ podman_containers.containers }}"
    when: item.State.Running is not defined or not item.State.Running
    loop_control:
      label: "{{ item.Name }}"