disk: "/dev/sdd"
vg_name: "cuarto-vg"
volumes:
  - name: "lv_data5"
    size: "1G"
    fstype: "ext4"
    mount_point: "/var/data3/nuevo_home"
  - name: "lv_data4"
    size: "1G"
    fstype: "xfs"
    mount_point: "/var/data4/nuevo"