---
- name: Verificar si el dispositivo existe
  ansible.builtin.stat:
    path: "{{ lvm_device }}"
  register: device_status

- name: Crear partición para LVM en {{ lvm_device }}
  community.general.parted:
    device: "{{ lvm_device }}"
    number: 1
    flags: [ lvm ]
    state: present
    part_end: "100%"
  register: partition_result
  when: device_status.stat.exists

- name: Crear volumen físico en la nueva partición
  command: pvcreate {{ lvm_device }}{{ lvm_partition_number }}
  when: device_status.stat.exists

- name: Añadir nuevo PV al VG (si no está añadido aún)
  command: vgextend {{ lvm_vg_name }} {{ lvm_device }}{{ lvm_partition_number }}
  when: "'/dev/sdd1' not in pv_create_result.msg"
  
- name: Extender volumen lógico {{ lvm_lv_name }}
  community.general.lvol:
    vg: "{{ lvm_vg_name }}"
    lv: "{{ lvm_lv_name }}"
    size: "{{ lvm_extend_size }}"
    resizefs: "{{ lvm_resize_fs }}"
