---
  - name: Obtener lista de IDs de contenedores
    ansible.builtin.command: docker ps -a -q
    register: container_ids

  - name: Obtener información de cada contenedor
    ansible.builtin.command: docker inspect {{ item }}
    loop: "{{ container_ids.stdout_lines }}"
    register: container_info

  - name: Mostrar información de los contenedores inspeccionados
    debug:
      var: container_info.results

  - name: Reiniciar contenedores que no están en estado running (Docker)
    community.docker.docker_container:
      name: "{{ item.Name | regex_replace('^/', '') }}"  # Quitar el prefijo '/'
      state: started
    loop: "{{ docker_containers | selectattr('State.Running', 'eq', false) | list }}"
    loop_control:
      label: "{{ item.Name | regex_replace('^/', '') }}"  # Mostrar nombres sin prefijo
    when: docker_containers | length > 0  # Asegurar que haya contenedores