---
  - name: Obtener información de contenedores detenidos
    ansible.builtin.command: docker inspect $(docker ps -aq)
    register: docker_containers_raw
  
  - name: Parsear datos de contenedores
    set_fact:
      docker_containers: "{{ docker_containers_raw.stdout | from_json }}"
  
  - name: Reiniciar contenedores que no están en estado running (Docker)
    community.docker.docker_container:
      name: "{{ item.Name | regex_replace('^/', '') }}"
      state: started
    loop: "{{ docker_containers | selectattr('State.Running', 'eq', false) | list }}"
    loop_control:
      label: "{{ item.Name | regex_replace('^/', '') }}"
    when: docker_containers | length > 0