---
  - name: Consultar información de todos los contenedores
    community.docker.docker_container:
      state: query
    register: container_info


  - name: Reiniciar contenedores que no estén en estado running (Docker)
    community.docker.docker_container:
      name: "{{ item.Name }}"
      state: started
    loop: "{{ docker_containers.containers | selectattr('State.Running', '!=', True) | list }}"
    loop_control:
      label: "{{ item.Name }}"