---
  - name: Obtener lista de IDs de contenedores
    ansible.builtin.command: docker ps -q
    register: container_ids

  - name: Obtener información de cada contenedor
    ansible.builtin.command: docker inspect {{ item }}
    loop: "{{ container_ids.stdout_lines }}"
    register: container_info
  
  - name: Mostrar información de los contenedores inspeccionados
    debug:
      var: container_info.results

  - name: Reiniciar contenedores que no estén en estado running (Docker)
    community.docker.docker_container:
      name: "{{ item.Name }}"
      state: started
    loop: "{{ docker_containers.containers | selectattr('State.Running', '!=', True) | list }}"
    loop_control:
      label: "{{ item.Name }}"