---
  - name: Obtener lista de IDs de contenedores
    ansible.builtin.command: docker ps -aq
    register: container_ids_raw
  
  - name: Inspeccionar contenedores
    ansible.builtin.command: docker inspect {{ container_ids_raw.stdout_lines | join(' ') }}
    register: docker_containers_raw
  
  - name: Convertir resultado de inspección en JSON
    set_fact:
      docker_containers: "{{ docker_containers_raw.stdout | from_json }}"
    
  - name: Reiniciar contenedores que no están en estado running (Docker)
    community.docker.docker_container:
      name: "{{ item.Name | regex_replace('^/', '') }}"
      state: started
    loop: "{{ docker_containers | selectattr('State.Running', 'eq', false) | list }}"
    loop_control:
      label: "{{ item.Name | regex_replace('^/', '') }}"
    when: docker_containers | length > 0