---
- name: Pull the cAdvisor image
  containers.podman.podman_image:
    name: "{{ cadvisor_image }}"
    tag: "{{ cadvisor_version }}"
    state: present

- name: Create the cAdvisor container
  containers.podman.podman_container:
    name: "{{ cadvisor_container_name }}"
    image: "{{ cadvisor_image }}:{{ cadvisor_version }}"
    state: started
    privileged: "{{ cadvisor_privileged }}"
    restart_policy: "{{ cadvisor_restart_policy }}"
    detach: true
  register: cadvisor_containe

- name: Add ports to cAdvisor container
  containers.podman.podman_container:
    name: "{{ cadvisor_container_name }}"
    ports:
      - "{{ item }}"
  with_items: "{{ cadvisor_ports }}"
  when: cadvisor_container.container.State.Status == "running"

- name: Add volumes to cAdvisor container
  containers.podman.podman_container:
    name: "{{ cadvisor_container_name }}"
    volumes:
      - "{{ item }}"
  with_items: "{{ cadvisor_volumes }}"
  when: cadvisor_container.container.State.Status == "running"