---
- name: Pull the cAdvisor image
  containers.podman.podman_image:
    name: "{{ cadvisor_image }}"
    tag: "{{ cadvisor_version }}"
    state: present

- name: Create the cAdvisor container with ports and volumes
containers.podman.podman_container:
  name: "{{ cadvisor_container_name }}"
  image: "{{ cadvisor_image }}:{{ cadvisor_version }}"
  state: started
  privileged: "{{ cadvisor_privileged }}"
  ports: "{{ item.ports | default(omit) }}"
  volumes: "{{ item.volumes | default(omit) }}"
  restart_policy: "{{ cadvisor_restart_policy }}"
loop: 
  - { ports: "8203:8080" }
  - { ports: "8300:9090" }
  - { volumes: "/:/rootfs:ro" }
  - { volumes: "/sys:/sys:ro" }
  - { volumes: "/var/run:/var/run:rw" }
  - { volumes: "/var/lib/docker/:/var/lib/docker:ro" }
  - { volumes: "/run/podman:/run/podman:rw" }